### ISSUE TITLE
After resharding some data is not in the correct shard database

### ISSUE THREAD

**Issue by mwillebrands** [pblrok/Sitecore.XDB.ReshardingTool#4]
Hi,

There seems to be a mismatch to how the tool is resharding the tables, as records end up in the wrong shard database after resharding.
The tables should be sharded based on the following sharding key:
| Table | Current Sharding Key | Expected Sharding Key | Correct |
| ------------- | ------------- | ------------ |--------------------|
| ContactFacet | ContactId | ContactId | :heavy_check_mark:	 |
| ContactIdentifiers | ContactId | ContactId | :heavy_check_mark:	 |
| Contacts | ContactId | ContactId | :heavy_check_mark:	 |
| InteractionFacets | InteractionId | ContactId | :x:	 |
| Interactions | InteractionId | ContactId | :x:	 |
| DeviceProfileFacets | DeviceProfileId | DeviceProfileId | :heavy_check_mark:	 |
| DeviceProfiles | DeviceProfileId | DeviceProfileId | :heavy_check_mark:	 |
| ContactIdentifiersIndex | ContactId | Identifier | :x:	 |

**Validation**
You can validate this by using the following scenario:
- Set up an empty Sitecore site with 2 shard databases
- Generate some XDB data by identifying a contact and having some interactions
- Create a new Shard Map manager with 2 databases
- Run the resharding tool to reshard data from the original shard databases to the two new shard databases
- Validate that the data is identical

You can use the following SQL query to validate that the data is identical (run it on both shards)
```sql

select count(*) as ContactFacets from (SELECT * FROM [original_shard1].[xdb_collection].[ContactFacets]
EXCEPT
SELECT * FROM [reshard_shard1].[xdb_collection].[Contactfacets]) contactFacets;


select count(*) as ContactIdentifiers from (SELECT * FROM [original_shard1].[xdb_collection].[ContactIdentifiers]
EXCEPT
SELECT * FROM [reshard_shard1].[xdb_collection].[ContactIdentifiers]) contactIdentifiers;


select count(*) as ContactIdentifiersIndex from (SELECT * FROM [original_shard1].[xdb_collection].[ContactIdentifiersIndex]
EXCEPT
SELECT * FROM [reshard_shard1].[xdb_collection].[ContactIdentifiersIndex]) contactIdentifiersIndex;


select count(*) as Contacts from (SELECT * FROM [original_shard1].[xdb_collection].[Contacts]
EXCEPT
SELECT * FROM [reshard_shard1].[xdb_collection].[Contacts]) contacts;


select count(*) as DeviceProfileFacets from (SELECT * FROM [original_shard1].[xdb_collection].[DeviceProfileFacets]
EXCEPT
SELECT * FROM [reshard_shard1].[xdb_collection].[DeviceProfileFacets]) deviceProfileFacets;


select count(*) as DeviceProfiles from (SELECT * FROM [original_shard1].[xdb_collection].[DeviceProfiles]
EXCEPT
SELECT * FROM [reshard_shard1].[xdb_collection].[DeviceProfiles]) deviceProfiles;


select count(*) as InteractionFacets from (SELECT * FROM [original_shard1].[xdb_collection].[InteractionFacets]
EXCEPT
SELECT * FROM [reshard_shard1].[xdb_collection].[InteractionFacets]) interactionFacets;


select count(*) as Interactions from (SELECT * FROM [original_shard1].[xdb_collection].[Interactions]
EXCEPT
SELECT * FROM [reshard_shard1].[xdb_collection].[Interactions]) interactions;
```

All output should be 0, as any other number indicates that there are differences between the two tables.

I've fixed this in https://github.com/pblrok/Sitecore.XDB.ReshardingTool/pull/3

**Comment by VadzimPapko** [comment]
PR #3 merged
